//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KampanyaKategori
    {
        public int id { get; set; }
        public int KampanyaFK { get; set; }
        public string KampanyaAdi { get; set; }
        public string KampanyaBanner { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Kampanya Kampanya { get; set; }
    }
}
