//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uyeler()
        {
            this.GirisYapan = new HashSet<GirisYapan>();
        }
    
        public int id { get; set; }
        public string isim { get; set; }
        public string Soyadı { get; set; }
        public string Mail { get; set; }
        public string Adres { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string telefon { get; set; }
        public string sifre { get; set; }
        public string sifreOnay { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GirisYapan> GirisYapan { get; set; }
    }
}
